"""Add multi-tenant support with Empresa and bot models

Revision ID: 25df3d127c72
Revises: 9a183e2ace86
Create Date: 2026-01-23 10:18:18.164216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25df3d127c72'
down_revision: Union[str, None] = '9a183e2ace86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_token', sa.Text(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=50), nullable=False),
    sa.Column('verify_token', sa.String(length=255), nullable=False),
    sa.Column('mercadopago_access_token', sa.Text(), nullable=True),
    sa.Column('mercadopago_public_key', sa.String(length=255), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_empresa_id'), 'empresa', ['id'], unique=False)
    op.create_index(op.f('ix_empresa_phone_number_id'), 'empresa', ['phone_number_id'], unique=True)
    op.create_table('configuracao_bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_dado', sa.String(length=20), nullable=True),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_empresa_chave', 'configuracao_bot', ['empresa_id', 'chave'], unique=True)
    op.create_index(op.f('ix_configuracao_bot_id'), 'configuracao_bot', ['id'], unique=False)
    op.add_column('painel_atendente', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.add_column('painel_atendente', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('painel_atendente', sa.Column('senha_hash', sa.String(length=255), nullable=True))
    op.drop_constraint('painel_atendente_user_id_key', 'painel_atendente', type_='unique')
    op.create_index('idx_empresa_user', 'painel_atendente', ['empresa_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_painel_atendente_empresa_id'), 'painel_atendente', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'painel_atendente', 'empresa', ['empresa_id'], ['id'])
    op.add_column('whatsapp_bot_chatsessao', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('whatsapp_bot_chatsessao', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.create_index('idx_empresa_whatsapp_sessao', 'whatsapp_bot_chatsessao', ['empresa_id', 'whatsapp_number'], unique=True)
    op.create_index(op.f('ix_whatsapp_bot_chatsessao_empresa_id'), 'whatsapp_bot_chatsessao', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_bot_chatsessao_id'), 'whatsapp_bot_chatsessao', ['id'], unique=False)
    op.create_foreign_key(None, 'whatsapp_bot_chatsessao', 'empresa', ['empresa_id'], ['id'])
    op.add_column('whatsapp_bot_cliente', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.drop_index('ix_whatsapp_bot_cliente_cpf', table_name='whatsapp_bot_cliente')
    op.create_index(op.f('ix_whatsapp_bot_cliente_cpf'), 'whatsapp_bot_cliente', ['cpf'], unique=False)
    op.drop_index('ix_whatsapp_bot_cliente_whatsapp_number', table_name='whatsapp_bot_cliente')
    op.create_index(op.f('ix_whatsapp_bot_cliente_whatsapp_number'), 'whatsapp_bot_cliente', ['whatsapp_number'], unique=False)
    op.create_index('idx_empresa_cpf', 'whatsapp_bot_cliente', ['empresa_id', 'cpf'], unique=True)
    op.create_index('idx_empresa_whatsapp', 'whatsapp_bot_cliente', ['empresa_id', 'whatsapp_number'], unique=True)
    op.create_index(op.f('ix_whatsapp_bot_cliente_empresa_id'), 'whatsapp_bot_cliente', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'whatsapp_bot_cliente', 'empresa', ['empresa_id'], ['id'])
    op.add_column('whatsapp_bot_mensagemlog', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.drop_index('idx_whatsapp_timestamp', table_name='whatsapp_bot_mensagemlog')
    op.create_index('idx_empresa_whatsapp_timestamp', 'whatsapp_bot_mensagemlog', ['empresa_id', 'whatsapp_number', 'timestamp'], unique=False)
    op.create_index(op.f('ix_whatsapp_bot_mensagemlog_empresa_id'), 'whatsapp_bot_mensagemlog', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'whatsapp_bot_mensagemlog', 'empresa', ['empresa_id'], ['id'])
    op.add_column('whatsapp_bot_tiposervico', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_whatsapp_bot_tiposervico_empresa_id'), 'whatsapp_bot_tiposervico', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'whatsapp_bot_tiposervico', 'empresa', ['empresa_id'], ['id'])
    op.add_column('whatsapp_bot_vagaagenda', sa.Column('empresa_id', sa.Integer(), nullable=False))
    op.drop_index('ix_whatsapp_bot_vagaagenda_data', table_name='whatsapp_bot_vagaagenda')
    op.create_index(op.f('ix_whatsapp_bot_vagaagenda_data'), 'whatsapp_bot_vagaagenda', ['data'], unique=False)
    op.create_index('idx_empresa_data', 'whatsapp_bot_vagaagenda', ['empresa_id', 'data'], unique=True)
    op.create_index(op.f('ix_whatsapp_bot_vagaagenda_empresa_id'), 'whatsapp_bot_vagaagenda', ['empresa_id'], unique=False)
    op.create_foreign_key(None, 'whatsapp_bot_vagaagenda', 'empresa', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_bot_vagaagenda', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_bot_vagaagenda_empresa_id'), table_name='whatsapp_bot_vagaagenda')
    op.drop_index('idx_empresa_data', table_name='whatsapp_bot_vagaagenda')
    op.drop_index(op.f('ix_whatsapp_bot_vagaagenda_data'), table_name='whatsapp_bot_vagaagenda')
    op.create_index('ix_whatsapp_bot_vagaagenda_data', 'whatsapp_bot_vagaagenda', ['data'], unique=True)
    op.drop_column('whatsapp_bot_vagaagenda', 'empresa_id')
    op.drop_constraint(None, 'whatsapp_bot_tiposervico', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_bot_tiposervico_empresa_id'), table_name='whatsapp_bot_tiposervico')
    op.drop_column('whatsapp_bot_tiposervico', 'empresa_id')
    op.drop_constraint(None, 'whatsapp_bot_mensagemlog', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_bot_mensagemlog_empresa_id'), table_name='whatsapp_bot_mensagemlog')
    op.drop_index('idx_empresa_whatsapp_timestamp', table_name='whatsapp_bot_mensagemlog')
    op.create_index('idx_whatsapp_timestamp', 'whatsapp_bot_mensagemlog', ['whatsapp_number', 'timestamp'], unique=False)
    op.drop_column('whatsapp_bot_mensagemlog', 'empresa_id')
    op.drop_constraint(None, 'whatsapp_bot_cliente', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_bot_cliente_empresa_id'), table_name='whatsapp_bot_cliente')
    op.drop_index('idx_empresa_whatsapp', table_name='whatsapp_bot_cliente')
    op.drop_index('idx_empresa_cpf', table_name='whatsapp_bot_cliente')
    op.drop_index(op.f('ix_whatsapp_bot_cliente_whatsapp_number'), table_name='whatsapp_bot_cliente')
    op.create_index('ix_whatsapp_bot_cliente_whatsapp_number', 'whatsapp_bot_cliente', ['whatsapp_number'], unique=True)
    op.drop_index(op.f('ix_whatsapp_bot_cliente_cpf'), table_name='whatsapp_bot_cliente')
    op.create_index('ix_whatsapp_bot_cliente_cpf', 'whatsapp_bot_cliente', ['cpf'], unique=True)
    op.drop_column('whatsapp_bot_cliente', 'empresa_id')
    op.drop_constraint(None, 'whatsapp_bot_chatsessao', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_bot_chatsessao_id'), table_name='whatsapp_bot_chatsessao')
    op.drop_index(op.f('ix_whatsapp_bot_chatsessao_empresa_id'), table_name='whatsapp_bot_chatsessao')
    op.drop_index('idx_empresa_whatsapp_sessao', table_name='whatsapp_bot_chatsessao')
    op.drop_column('whatsapp_bot_chatsessao', 'empresa_id')
    op.drop_column('whatsapp_bot_chatsessao', 'id')
    op.drop_constraint(None, 'painel_atendente', type_='foreignkey')
    op.drop_index(op.f('ix_painel_atendente_empresa_id'), table_name='painel_atendente')
    op.drop_index('idx_empresa_user', table_name='painel_atendente')
    op.create_unique_constraint('painel_atendente_user_id_key', 'painel_atendente', ['user_id'])
    op.drop_column('painel_atendente', 'senha_hash')
    op.drop_column('painel_atendente', 'email')
    op.drop_column('painel_atendente', 'empresa_id')
    op.drop_index(op.f('ix_configuracao_bot_id'), table_name='configuracao_bot')
    op.drop_index('idx_empresa_chave', table_name='configuracao_bot')
    op.drop_table('configuracao_bot')
    op.drop_index(op.f('ix_empresa_phone_number_id'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_id'), table_name='empresa')
    op.drop_table('empresa')
    # ### end Alembic commands ###
