"""Initial migration with all models

Revision ID: 9a183e2ace86
Revises: 
Create Date: 2026-01-22 00:43:20.953962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a183e2ace86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('painel_atendente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('ultima_atividade', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('pode_atender', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_painel_atendente_id'), 'painel_atendente', ['id'], unique=False)
    op.create_table('whatsapp_bot_chatsessao',
    sa.Column('whatsapp_number', sa.String(length=20), nullable=False),
    sa.Column('estado_atual', sa.String(length=100), nullable=True),
    sa.Column('dados_temporarios', sa.JSON(), nullable=True),
    sa.Column('ultima_interacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('whatsapp_number')
    )
    op.create_index(op.f('ix_whatsapp_bot_chatsessao_whatsapp_number'), 'whatsapp_bot_chatsessao', ['whatsapp_number'], unique=False)
    op.create_table('whatsapp_bot_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('endereco_residencial', sa.String(length=255), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_bot_cliente_cpf'), 'whatsapp_bot_cliente', ['cpf'], unique=True)
    op.create_index(op.f('ix_whatsapp_bot_cliente_id'), 'whatsapp_bot_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_bot_cliente_whatsapp_number'), 'whatsapp_bot_cliente', ['whatsapp_number'], unique=True)
    op.create_table('whatsapp_bot_mensagemlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('direcao', sa.String(length=10), nullable=False),
    sa.Column('tipo_mensagem', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('dados_extras', sa.JSON(), nullable=True),
    sa.Column('estado_sessao', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_direcao_timestamp', 'whatsapp_bot_mensagemlog', ['direcao', 'timestamp'], unique=False)
    op.create_index('idx_whatsapp_timestamp', 'whatsapp_bot_mensagemlog', ['whatsapp_number', 'timestamp'], unique=False)
    op.create_index(op.f('ix_whatsapp_bot_mensagemlog_id'), 'whatsapp_bot_mensagemlog', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_bot_mensagemlog_timestamp'), 'whatsapp_bot_mensagemlog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_whatsapp_bot_mensagemlog_whatsapp_number'), 'whatsapp_bot_mensagemlog', ['whatsapp_number'], unique=False)
    op.create_table('whatsapp_bot_tiposervico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_bot_tiposervico_id'), 'whatsapp_bot_tiposervico', ['id'], unique=False)
    op.create_table('whatsapp_bot_vagaagenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quantidade_vagas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_bot_vagaagenda_data'), 'whatsapp_bot_vagaagenda', ['data'], unique=True)
    op.create_index(op.f('ix_whatsapp_bot_vagaagenda_id'), 'whatsapp_bot_vagaagenda', ['id'], unique=False)
    op.create_table('painel_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=False),
    sa.Column('atendente_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atribuido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_mensagem_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['atendente_id'], ['painel_atendente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_whatsapp_status', 'painel_atendimento', ['whatsapp_number', 'status'], unique=False)
    op.create_index(op.f('ix_painel_atendimento_id'), 'painel_atendimento', ['id'], unique=False)
    op.create_index(op.f('ix_painel_atendimento_ultima_mensagem_em'), 'painel_atendimento', ['ultima_mensagem_em'], unique=False)
    op.create_index(op.f('ix_painel_atendimento_whatsapp_number'), 'painel_atendimento', ['whatsapp_number'], unique=False)
    op.create_table('whatsapp_bot_contratacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico_id', sa.Integer(), nullable=False),
    sa.Column('data_contratacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status_pagamento', sa.String(length=20), nullable=True),
    sa.Column('endereco_servico', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['whatsapp_bot_cliente.id'], ),
    sa.ForeignKeyConstraint(['tipo_servico_id'], ['whatsapp_bot_tiposervico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_pagamento', 'whatsapp_bot_contratacao', ['status_pagamento'], unique=False)
    op.create_index(op.f('ix_whatsapp_bot_contratacao_id'), 'whatsapp_bot_contratacao', ['id'], unique=False)
    op.create_table('whatsapp_bot_reclamacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('data_reclamacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['whatsapp_bot_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_bot_reclamacao_id'), 'whatsapp_bot_reclamacao', ['id'], unique=False)
    op.create_table('whatsapp_bot_agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contratacao_id', sa.Integer(), nullable=False),
    sa.Column('data_agendada_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['whatsapp_bot_contratacao.id'], ),
    sa.ForeignKeyConstraint(['data_agendada_id'], ['whatsapp_bot_vagaagenda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contratacao_id')
    )
    op.create_index(op.f('ix_whatsapp_bot_agendamento_id'), 'whatsapp_bot_agendamento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_bot_agendamento_id'), table_name='whatsapp_bot_agendamento')
    op.drop_table('whatsapp_bot_agendamento')
    op.drop_index(op.f('ix_whatsapp_bot_reclamacao_id'), table_name='whatsapp_bot_reclamacao')
    op.drop_table('whatsapp_bot_reclamacao')
    op.drop_index(op.f('ix_whatsapp_bot_contratacao_id'), table_name='whatsapp_bot_contratacao')
    op.drop_index('idx_status_pagamento', table_name='whatsapp_bot_contratacao')
    op.drop_table('whatsapp_bot_contratacao')
    op.drop_index(op.f('ix_painel_atendimento_whatsapp_number'), table_name='painel_atendimento')
    op.drop_index(op.f('ix_painel_atendimento_ultima_mensagem_em'), table_name='painel_atendimento')
    op.drop_index(op.f('ix_painel_atendimento_id'), table_name='painel_atendimento')
    op.drop_index('idx_whatsapp_status', table_name='painel_atendimento')
    op.drop_table('painel_atendimento')
    op.drop_index(op.f('ix_whatsapp_bot_vagaagenda_id'), table_name='whatsapp_bot_vagaagenda')
    op.drop_index(op.f('ix_whatsapp_bot_vagaagenda_data'), table_name='whatsapp_bot_vagaagenda')
    op.drop_table('whatsapp_bot_vagaagenda')
    op.drop_index(op.f('ix_whatsapp_bot_tiposervico_id'), table_name='whatsapp_bot_tiposervico')
    op.drop_table('whatsapp_bot_tiposervico')
    op.drop_index(op.f('ix_whatsapp_bot_mensagemlog_whatsapp_number'), table_name='whatsapp_bot_mensagemlog')
    op.drop_index(op.f('ix_whatsapp_bot_mensagemlog_timestamp'), table_name='whatsapp_bot_mensagemlog')
    op.drop_index(op.f('ix_whatsapp_bot_mensagemlog_id'), table_name='whatsapp_bot_mensagemlog')
    op.drop_index('idx_whatsapp_timestamp', table_name='whatsapp_bot_mensagemlog')
    op.drop_index('idx_direcao_timestamp', table_name='whatsapp_bot_mensagemlog')
    op.drop_table('whatsapp_bot_mensagemlog')
    op.drop_index(op.f('ix_whatsapp_bot_cliente_whatsapp_number'), table_name='whatsapp_bot_cliente')
    op.drop_index(op.f('ix_whatsapp_bot_cliente_id'), table_name='whatsapp_bot_cliente')
    op.drop_index(op.f('ix_whatsapp_bot_cliente_cpf'), table_name='whatsapp_bot_cliente')
    op.drop_table('whatsapp_bot_cliente')
    op.drop_index(op.f('ix_whatsapp_bot_chatsessao_whatsapp_number'), table_name='whatsapp_bot_chatsessao')
    op.drop_table('whatsapp_bot_chatsessao')
    op.drop_index(op.f('ix_painel_atendente_id'), table_name='painel_atendente')
    op.drop_table('painel_atendente')
    # ### end Alembic commands ###
